"""全局配置 handler：读写 data/config.json。"""

from __future__ import annotations

import json
import os

from shared import errors
from shared.result import Result


def _config_path():
    return os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "..", "data", "config.json",
    )


DEFAULT_CONFIG = {
    "ai": {
        "provider": "deterministic",
        "ollama": {"baseUrl": "http://127.0.0.1:11434", "model": ""},
        "cloud": {"provider": "", "model": "", "apiKey": "", "baseUrl": ""},
    },
    "delivery": {"defaultMode": "package_export", "autoGenerateDocs": True},
    "inventory": {"ttlHours": 24, "autoRefreshPrompt": True},
}


def _text_value(value):
    if isinstance(value, list):
        for item in value:
            text = str(item or "").strip()
            if text:
                return text
        return ""
    return str(value or "").strip()


def _normalize_ai_config(cfg):
    cfg = cfg or {}
    ai = cfg.setdefault("ai", {})
    ai["provider"] = _text_value(ai.get("provider")) or DEFAULT_CONFIG["ai"]["provider"]

    ollama = ai.setdefault("ollama", {})
    ollama["baseUrl"] = _text_value(ollama.get("baseUrl")) or DEFAULT_CONFIG["ai"]["ollama"]["baseUrl"]
    ollama["model"] = _text_value(ollama.get("model"))

    cloud = ai.setdefault("cloud", {})
    cloud["provider"] = _text_value(cloud.get("provider"))
    cloud["model"] = _text_value(cloud.get("model"))
    cloud["apiKey"] = _text_value(cloud.get("apiKey"))
    cloud["baseUrl"] = _text_value(cloud.get("baseUrl"))
    return cfg


def _read():
    path = _config_path()
    if os.path.isfile(path):
        with open(path, encoding="utf-8") as h:
            return _normalize_ai_config(json.load(h))
    return _normalize_ai_config(dict(DEFAULT_CONFIG))


def _write(cfg):
    cfg = _normalize_ai_config(cfg)
    path = _config_path()
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as h:
        json.dump(cfg, h, ensure_ascii=False, indent=2)


def get_workspace(**_):
    return Result.success(_read())


def put_workspace(body, **_):
    cfg = _read()
    if body:
        _deep_merge(cfg, body)
    _write(cfg)
    return Result.success(cfg)


def _deep_merge(base, update):
    for k, v in update.items():
        if isinstance(v, dict) and isinstance(base.get(k), dict):
            _deep_merge(base[k], v)
        else:
            base[k] = v


def test_ollama(body, **_):
    """测试 Ollama 连通性，并返回已安装的模型列表。"""
    import json as _json, urllib.request as _req
    body = body or {}
    url = (body.get("baseUrl") or "http://127.0.0.1:11434").rstrip("/") + "/api/tags"
    try:
        resp = _req.urlopen(_req.Request(url), timeout=5)
        data = _json.loads(resp.read().decode())
        models = [m["name"] for m in data.get("models", [])]
        return Result.success({"reachable": True, "models": models})
    except Exception as e:
        return Result.success({"reachable": False, "reason": str(e), "models": []})


def test_cloud(body, **_):
    """测试 Cloud API：发一条极简请求验证 key + model 是否有效。"""
    import json as _json, urllib.request as _req
    body = body or {}
    base = (body.get("baseUrl") or "").rstrip("/")
    model = body.get("model") or ""
    api_key = body.get("apiKey") or ""
    if not base or not model:
        return Result.success({"reachable": False, "reason": "缺少 baseUrl 或 model"})
    url = base + "/chat/completions"
    payload = _json.dumps({
        "model": model,
        "messages": [{"role": "user", "content": "hi"}],
        "max_tokens": 5,
    }).encode()
    req = _req.Request(url, data=payload, method="POST")
    req.add_header("Content-Type", "application/json")
    req.add_header("Authorization", "Bearer " + api_key)
    try:
        resp = _req.urlopen(req, timeout=10)
        data = _json.loads(resp.read().decode())
        return Result.success({"reachable": True, "model": model, "response": str(data.get("choices", [{}])[0].get("message", {}).get("content", ""))[:80]})
    except _req.HTTPError as e:
        body_text = ""
        try: body_text = e.read().decode()[:200]
        except: pass
        return Result.success({"reachable": False, "reason": "HTTP %d: %s" % (e.code, body_text)})
    except Exception as e:
        return Result.success({"reachable": False, "reason": str(e)})


def generate_namespace(body, **_):
    """用配置的 AI 模型将公司名转为英文命名空间。"""
    import json as _json, urllib.request as _req
    import re

    name = (body or {}).get("name", "").strip()
    if not name:
        return Result.failure("缺少 name", code=errors.VALIDATION_ERROR)

    cfg = _read()
    ai = cfg.get("ai", {})
    provider = ai.get("provider", "deterministic")

    prompt = (
        "你是软件包命名助手。请把公司名称改写成适合 Python/Plone addon 的 namespace。"
        "只返回一个结果，不要解释，不要引号，不要代码块。\n"
        "规则：\n"
        "1. 结果要短，优先 4-8 个字符，最长不要超过 12 个字符。\n"
        "2. 只用小写英文字母，必要时可带数字；不要空格、横线、下划线或其他符号。\n"
        "3. 如果公司名有自然、简洁、行业里常见的英文表达，就直接用英文。\n"
        "4. 如果不适合直接翻成自然英文，使用简短拼音，避免生硬直译。\n"
        "5. 结果必须适合做 namespace，像一个稳定、简洁的包名前缀。\n"
        "示例：\n"
        "- 北京诺诚 -> nuocheng\n"
        "- 本地测试 -> localtest\n"
        "- 华检科技 -> huajian\n\n"
        "公司名称：%s\n\n命名空间：" % name
    )

    try:
        if provider == "ollama":
            ollama = ai.get("ollama", {})
            url = (ollama.get("baseUrl", "http://127.0.0.1:11434")).rstrip("/") + "/api/generate"
            payload = _json.dumps({
                "model": ollama.get("model", ""),
                "prompt": prompt, "stream": False,
                "options": {"temperature": 0.1},
            }).encode()
            req = _req.Request(url, data=payload, method="POST")
            req.add_header("Content-Type", "application/json")
            resp = _req.urlopen(req, timeout=30)
            data = _json.loads(resp.read().decode())
            ns = data.get("response", "").strip().lower()
        else:
            cloud = ai.get("cloud", {})
            url = (cloud.get("baseUrl", "")).rstrip("/") + "/chat/completions"
            payload = _json.dumps({
                "model": cloud.get("model", ""),
                "messages": [{"role": "user", "content": prompt}],
                "max_tokens": 24, "temperature": 0.1,
            }).encode()
            req = _req.Request(url, data=payload, method="POST")
            req.add_header("Content-Type", "application/json")
            req.add_header("Authorization", "Bearer " + cloud.get("apiKey", ""))
            resp = _req.urlopen(req, timeout=30)
            data = _json.loads(resp.read().decode())
            ns = data["choices"][0]["message"]["content"].strip().lower()

        ns = ns.splitlines()[0].strip().strip("`'\"")
        ns = re.sub(r"[^a-z0-9]", "", ns)
        if len(ns) > 12:
            ns = ns[:12]
        if not ns or not re.match(r"^[a-z]", ns):
            ns = "co" + ns[:10]
        return Result.success({"namespace": ns})
    except Exception as e:
        # AI 不可用 → 用简单规则兜底
        ns = re.sub(r"[^a-z0-9]", "", name.lower())[:12]
        if not ns:
            ns = "co" + hex(hash(name) & 0xFFFF)[2:]
        return Result.success({"namespace": ns, "fallback": True,
                               "reason": str(e)[:80]})


def register(router) -> None:
    router.get("/api/config/workspace", get_workspace)
    router.put("/api/config/workspace", put_workspace)
    router.post("/api/config/test-ollama", test_ollama)
    router.post("/api/config/test-cloud", test_cloud)
    router.post("/api/config/generate-namespace", generate_namespace)
