import { useEffect, useState } from 'react';
import {
  App, Button, Card, Divider, Form, Input, InputNumber, Radio,
  Select, Space, Switch, Typography,
} from 'antd';
import { ThunderboltOutlined, RobotOutlined } from '@ant-design/icons';
import { apiClient } from '@/core/services/apiClient';

const { Title, Text } = Typography;

interface Config {
  ai: {
    provider: string;
    ollama: { baseUrl: string; model: string | string[] };
    cloud: { provider: string; model: string; apiKey: string; baseUrl: string };
  };
  delivery: { defaultMode: string; autoGenerateDocs: boolean };
  inventory: { ttlHours: number; autoRefreshPrompt: boolean };
}

const CLOUD_PROVIDERS = [
  { value: 'deepseek', label: 'DeepSeek', baseUrl: 'https://api.deepseek.com/v1',
    models: ['deepseek-chat', 'deepseek-reasoner', 'deepseek-v3', 'deepseek-r1'], desc: 'chat = V4(通用·最新)  reasoner = R1(推理)  v3/r1 = 独立版本' },
  { value: 'alibaba', label: '阿里云 百炼', baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    models: ['qwen3-max', 'qwen3-plus', 'qwen3-turbo', 'qwen-max', 'qwen-plus'] },
  { value: 'zhipu', label: '智谱 GLM', baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    models: ['glm-4.5', 'glm-4.5-flash', 'glm-4-plus', 'glm-4-flash'] },
  { value: 'moonshot', label: '月之暗面 Kimi', baseUrl: 'https://api.moonshot.cn/v1',
    models: ['moonshot-v1-8k', 'moonshot-v1-32k', 'moonshot-v1-128k'] },
  { value: 'openai', label: 'OpenAI', baseUrl: 'https://api.openai.com/v1',
    models: ['gpt-4.1', 'gpt-4.1-mini', 'gpt-4o', 'gpt-4o-mini'] },
  { value: 'custom', label: '自定义', baseUrl: '',
    models: [] },
];

const DD = {
  ai: { provider: 'deterministic', ollama: { baseUrl: 'http://127.0.0.1:11434', model: '' }, cloud: { provider: '', model: '', apiKey: '', baseUrl: '' } },
  delivery: { defaultMode: 'package_export', autoGenerateDocs: true },
  inventory: { ttlHours: 24, autoRefreshPrompt: true },
};

export default function SettingsPage() {
  const { message } = App.useApp();
  const [cfg, setCfg] = useState<Config>(DD as Config);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);

  const load = () => apiClient.get<Config>('/config/workspace')
    .then(setCfg).finally(() => setLoading(false));
  useEffect(() => { load(); }, []);

  const save = async () => {
    setSaving(true);
    try { await apiClient.put('/config/workspace', cfg); message.success('已保存'); }
    catch { message.error('保存失败'); }
    finally { setSaving(false); }
  };

  const setAi = (patch: Partial<Config['ai']>) => {
    const next = { ...cfg, ai: { ...cfg.ai, ...patch } };
    setCfg(next);
    // 立即保存 provider 切换，状态栏实时跟
    apiClient.put('/config/workspace', next).then(() => {
      window.dispatchEvent(new CustomEvent('aiconfig-changed', { detail: next.ai }));
    }).catch(() => {});
  };
  const setOllama = (patch: Partial<Config['ai']['ollama']>) => setCfg(prev => ({ ...prev, ai: { ...prev.ai, ollama: { ...prev.ai.ollama, ...patch } } }));
  const setCloud = (patch: Partial<Config['ai']['cloud']>) => setCfg(prev => ({ ...prev, ai: { ...prev.ai, cloud: { ...prev.ai.cloud, ...patch } } }));

  const provider = cfg.ai.provider;
  const ollamaModel = Array.isArray(cfg.ai.ollama.model) ? (cfg.ai.ollama.model[0] || '') : (cfg.ai.ollama.model || '');

  // ── 测试 Ollama + 拉取模型列表 ──
  const [testingO, setTestingO] = useState(false);
  const [ollamaModels, setOllamaModels] = useState<string[]>([]);
  const testOllama = async (silent = false) => {
    setTestingO(true);
    try {
      const r = await apiClient.post<{ reachable: boolean; reason?: string; models: string[] }>(
        '/config/test-ollama', { baseUrl: cfg.ai.ollama.baseUrl });
      if (r.reachable) {
        setOllamaModels(r.models || []);
        if (!silent) {
          message.success(`Ollama 在线，${r.models?.length || 0} 个模型`);
        }
      } else {
        setOllamaModels([]);
        if (!silent) {
          message.warning(`无法连接: ${r.reason || '未知'}`);
        }
      }
    } catch {
      setOllamaModels([]);
      if (!silent) {
        message.error('测试失败');
      }
    }
    finally { setTestingO(false); }
  };
  // 进入 Ollama 配置时自动拉一次
  useEffect(() => {
    if (provider === 'ollama' && cfg.ai.ollama.baseUrl) {
      void testOllama(true);
    }
  }, [provider]);

  // ── 测试 Cloud API ──
  const [testingC, setTestingC] = useState(false);
  const testCloud = async () => {
    setTestingC(true);
    try {
      const r = await apiClient.post<{ reachable: boolean; reason?: string; response?: string }>(
        '/config/test-cloud', { baseUrl: cfg.ai.cloud.baseUrl, model: cfg.ai.cloud.model, apiKey: cfg.ai.cloud.apiKey });
      if (r.reachable) message.success('Cloud API 连接成功');
      else message.error('连接失败: ' + (r.reason || '未知'));
    } catch { message.error('测试失败'); }
    finally { setTestingC(false); }
  };

  // ── 选云厂商时自动填 baseUrl + 默认 model ──
  const selCloudProvider = (p: string) => {
    const info = CLOUD_PROVIDERS.find(c => c.value === p);
    setCloud({ provider: p, baseUrl: info?.baseUrl || '', model: (info?.models || [])[0] || '' });
  };

  const cloudInfo = CLOUD_PROVIDERS.find(c => c.value === cfg.ai.cloud.provider);

  return (
    <div style={{ maxWidth: 700 }}>
      <Title level={4} style={{ marginTop: 0 }}>⚙️ 设置</Title>

      <Card title={<Space><RobotOutlined /> AI 引擎</Space>} loading={loading}>
        <Form layout="vertical">
          <Form.Item label="默认引擎">
            <Radio.Group value={provider} onChange={e => setAi({ provider: e.target.value })}>
              <Radio.Button value="deterministic">规则引擎（离线）</Radio.Button>
              <Radio.Button value="ollama">Ollama（本地）</Radio.Button>
              <Radio.Button value="cloud">Cloud API（公网）</Radio.Button>
            </Radio.Group>
          </Form.Item>

          {/* Ollama */}
          {provider === 'ollama' && (
            <Card size="small" type="inner" title="Ollama 配置" style={{ marginBottom: 16 }}>
              <Form.Item label="API 地址">
                <Input value={cfg.ai.ollama.baseUrl} onChange={e => setOllama({ baseUrl: e.target.value })} />
              </Form.Item>
              <Form.Item label="模型" help={ollamaModels.length > 0 ? `已检测到 ${ollamaModels.length} 个模型` : '点击"测试连通性"拉取模型列表'}>
                <Select
                  value={ollamaModel ? [ollamaModel] : undefined}
                  showSearch
                  placeholder="选择或输入模型名"
                  onChange={v => setOllama({ model: Array.isArray(v) ? (v[0] || '') : v })}
                  filterOption={(input, option) => (option?.label as string || '').toLowerCase().includes(input.toLowerCase())}
                  options={[
                    ...ollamaModels.map(m => ({ value: m, label: m })),
                    ...(ollamaModel && !ollamaModels.includes(ollamaModel)
                      ? [{ value: ollamaModel, label: `${ollamaModel}（手动输入）` }] : []),
                  ]}
                  notFoundContent={testingO ? '检测中…' : '无历史记录，可手动输入模型名后回车'}
                  mode="tags"
                  maxCount={1}
                  tokenSeparators={[',']}
                  style={{ width: '100%' }}
                />
              </Form.Item>
              <Button icon={<ThunderboltOutlined />} loading={testingO} onClick={testOllama}>测试连通性并拉取模型</Button>
            </Card>
          )}

          {/* Cloud API */}
          {provider === 'cloud' && (
            <Card size="small" type="inner" title="Cloud API 配置" style={{ marginBottom: 16 }}>
              <Form.Item label="服务商">
                <Select value={cfg.ai.cloud.provider || undefined} placeholder="选择服务商"
                  onChange={selCloudProvider}
                  options={CLOUD_PROVIDERS.map(c => ({ value: c.value, label: c.label }))} />
              </Form.Item>
              {cloudInfo && (
                <>
                  <Form.Item label="API 地址">
                    <Input value={cfg.ai.cloud.baseUrl} onChange={e => setCloud({ baseUrl: e.target.value })} placeholder={cloudInfo.baseUrl || 'https://...'} />
                  </Form.Item>
                  <Form.Item label="模型">
                    {cfg.ai.cloud.provider === 'custom' ? (
                      <Input value={cfg.ai.cloud.model} onChange={e => setCloud({ model: e.target.value })} placeholder="输入模型名" />
                    ) : (
                      <Select value={cfg.ai.cloud.model || undefined} onChange={v => setCloud({ model: v })}
                        options={(cloudInfo.models || []).map(m => ({ value: m, label: m }))} />
                    )}
                  </Form.Item>
                  {cfg.ai.cloud.provider === 'deepseek' && (
                    <Text type="secondary" style={{ fontSize: 12 }}>deepseek-chat = V4（通用对话·最新） · deepseek-reasoner = R1（深度推理）</Text>
                  )}
                </>
              )}
              <Form.Item label="API Key">
                <Input.Password value={cfg.ai.cloud.apiKey} onChange={e => setCloud({ apiKey: e.target.value })} placeholder="sk-..." />
              </Form.Item>
              <Button icon={<ThunderboltOutlined />} loading={testingC} onClick={testCloud}>测试连通性</Button>
              <Text type="secondary" style={{ fontSize: 12, marginLeft: 12 }}>API Key 仅保存在本地 data/config.json，不会上传。</Text>
            </Card>
          )}
        </Form>
      </Card>

      <Divider />

      <Card title="交付偏好" loading={loading}>
        <Form layout="vertical">
          <Form.Item label="默认交付模式">
            <Radio.Group value={cfg.delivery.defaultMode} onChange={e => setCfg(prev => ({ ...prev, delivery: { ...prev.delivery, defaultMode: e.target.value } }))}>
              <Radio value="manual_copy">manual_copy</Radio>
              <Radio value="package_export">ZIP 打包</Radio>
            </Radio.Group>
          </Form.Item>
          <Form.Item label="自动生成部署文档">
            <Switch checked={cfg.delivery.autoGenerateDocs} onChange={v => setCfg(prev => ({ ...prev, delivery: { ...prev.delivery, autoGenerateDocs: v } }))} />
          </Form.Item>
        </Form>
      </Card>

      <Divider />

      <Card title="Inventory" loading={loading}>
        <Form layout="vertical">
          <Form.Item label="快照有效期（小时）">
            <InputNumber value={cfg.inventory.ttlHours} onChange={v => v && setCfg(prev => ({ ...prev, inventory: { ...prev.inventory, ttlHours: v } }))} />
          </Form.Item>
          <Form.Item label="到期自动提醒">
            <Switch checked={cfg.inventory.autoRefreshPrompt} onChange={v => setCfg(prev => ({ ...prev, inventory: { ...prev.inventory, autoRefreshPrompt: v } }))} />
          </Form.Item>
        </Form>
      </Card>

      <div style={{ marginTop: 24 }}>
        <Button type="primary" size="large" onClick={save} loading={saving}>保存配置</Button>
      </div>
    </div>
  );
}
